console.log("Hello, World!");
console.log("This is a test message.");
window.alert("Virus Alert!");
window.alert("Hacked by XYZ!");

//I love you

/*Hot dog
tinapay
*/

document.getElementById("MyH1").textContent = "JavaScript Example";
document.getElementById("MyP").textContent = "This is an updated JavaScript example.";



let x;
x = 500
let y;
y = 300;

let age= 21;
let price= 800.50;
let gpa= 3.5;

let firstName= "Jim";
let lastName= "Milton";
let email= "jim.milton69@example.com";

let online= true;
let ForSale= false;

console.log (x);
console.log (y);
console.log (x + y);

console.log (age);
console.log (price);
console.log (gpa);

console.log (`My name is ${firstName} ${lastName}.`);
console.log (`I am ${age} years old and my GPA is ${gpa}.`);
console.log (`i have ${x} pesos in me and ${y} on my bank account`);
console.log (`The price of alcohol is ${price}.`);
console.log (`Is online?: ${online}`);
console.log (`You can contact me at ${email}.`);
console.log (`Is this item alcohol for sale? ${ForSale}`);

console.log (typeof x);
console.log (typeof firstName);
console.log (typeof email);
console.log (typeof online);
console.log (typeof ForSale);

document.getElementById("p1").textContent = `My name is ${firstName} ${lastName}.`;
document.getElementById("p2").textContent = `I am ${age} years old and my GPA is ${gpa}.`;
document.getElementById("p3").textContent = `I have ${x} pesos in me and ${y} on my bank account.`;
